#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(OPENTRACKTRACKERDEEPFACE_LIB)
#  define OPENTRACKTRACKERDEEPFACE_EXPORT Q_DECL_EXPORT
# else
#  define OPENTRACKTRACKERDEEPFACE_EXPORT Q_DECL_IMPORT
# endif
#else
# define OPENTRACKTRACKERDEEPFACE_EXPORT
#endif
